language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"

# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# run test and report test-coverage to coveralls.io
script:
  - "coverage run --source=v1 -m pytest && coverage report"
  - "coveralls"


after_success:
  - "coveralls"
